version: "2"
services:
  decision-manager:
    image: jbossdemocentral/rhdm7-qlb-loan-demo:latest
    ports:
      - 8080:8080
      - 9990:9990
      - 9999:9999
#    entrypoint: "/bin/true"
  application-ui:
    image: jbossdemocentral/rhdm7-qlb-loan-demo-ui:latest
    links:
      - decision-manager:decision-manager
    ports:
      - 3000:3000
